# Generated by Django 5.0.2 on 2026-04-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_contenedor', '0002_add_abreviacion_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocontenedor',
            name='requiere_vacio',
            field=models.BooleanField(default=True),
        ),
    ]
