# Generated by Django 5.1.1 on 2024-11-22 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
        ('tipo_contenedor', '0001_initial'),
        ('tipo_unidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30, unique=True)),
                ('cantidad_por_bulto', models.SmallIntegerField()),
                ('peso_aproximado', models.FloatField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria')),
                ('tipo_contenedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_contenedor.tipocontenedor')),
                ('tipo_unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_unidad.tipounidad')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
    ]
