# Generated by Django 5.0.2 on 2026-03-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad_por_bulto',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='peso_aproximado',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
