# Generated by Django 5.1.5 on 2025-02-24 00:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(2)])),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'provincia',
            },
        ),
    ]
