# Generated by Django 5.0.2 on 2026-04-22 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compra', '0003_fix_importe_bruto'),
        ('tipo_contenedor', '0002_add_abreviacion_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraVacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacios', to='compra.compra')),
                ('tipo_contenedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_contenedor.tipocontenedor')),
            ],
            options={
                'db_table': 'compra_vacio',
            },
        ),
    ]
