# Generated by Django 5.1.5 on 2026-02-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_precios_producto', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='listapreciosproducto',
            constraint=models.UniqueConstraint(
                fields=['lista_precios', 'producto'],
                name='unique_lista_producto'
            ),
        ),
    ]
