# Generated by Django 5.0.2 on 2026-03-11 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_precios_producto', '0002_unique_lista_producto'),
        ('tipo_venta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listapreciosproducto',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='listapreciosproducto',
            name='tipo_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tipo_venta.tipoventa'),
        ),
    ]
