# Generated by Django 5.0.2 on 2026-03-11 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_precios', '0001_initial'),
        ('lista_precios_producto', '0004_data_migration_tipo_venta_precio'),
        ('producto', '0001_initial'),
        ('tipo_venta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listapreciosproducto',
            name='precio_bulto',
        ),
        migrations.RemoveField(
            model_name='listapreciosproducto',
            name='precio_unitario',
        ),
        migrations.AlterField(
            model_name='listapreciosproducto',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='listapreciosproducto',
            name='tipo_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipo_venta.tipoventa'),
        ),
        migrations.AddConstraint(
            model_name='listapreciosproducto',
            constraint=models.UniqueConstraint(fields=('lista_precios', 'producto', 'tipo_venta'), name='unique_lista_producto_tipo_venta'),
        ),
    ]
