# Generated by Django 5.1.3 on 2024-12-04 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
