# Generated by Django 5.1.5 on 2026-08-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_add_email_verification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Domicilio'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Foto de perfil'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono'),
        ),
    ]
