# Generated by Django 5.0.2 on 2026-08-31 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0003_usuario_address_usuario_avatar_usuario_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación'),
        ),
    ]
