# Generated by Django 5.0.2 on 2026-08-31 22:22

from django.db import migrations
from django.db.models import F, Q


def backfill_approved_at(apps, schema_editor):
    """
    Usuarios que ya estaban activos o que ya iniciaron sesión alguna vez fueron
    revisados en algún momento (aunque no quedara registrado antes de este
    campo) — se les marca approved_at con date_joined como aproximación
    histórica, para que no aparezcan como "pendientes de aprobación" de golpe.
    Solo queda approved_at=None quien nunca inició sesión y nunca estuvo activo.
    """
    Usuario = apps.get_model('autenticacion', 'Usuario')
    Usuario.objects.filter(
        Q(is_active=True) | Q(last_login__isnull=False)
    ).update(approved_at=F('date_joined'))


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0004_usuario_approved_at'),
    ]

    operations = [
        migrations.RunPython(backfill_approved_at, reverse_noop),
    ]
