# Generated by Django 5.1.5 on 2026-09-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0005_backfill_approved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='auth_provider',
            field=models.CharField(choices=[('local', 'Local'), ('google', 'Google')], default='local', max_length=20, verbose_name='Proveedor de autenticación'),
        ),
    ]
