# Generated by Django 5.0.2 on 2026-05-06 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cae',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='cae_vto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='numero_comprobante',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
