# Generated by Django 5.0.2 on 2026-03-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_factura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipofactura',
            name='descripcion',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
