# Generated by Django 5.0.2 on 2026-03-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_factura', '0002_alter_tipofactura_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipofactura',
            name='abreviatura',
            field=models.CharField(default='R', max_length=3, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipofactura',
            name='descripcion',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
