# Generated by Django 5.1.5 on 2025-02-24 00:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('municipio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_length', message='El ID debe tener entre 8 y 10 dígitos.', regex='^\\d{8,10}$')])),
                ('nombre', models.CharField(max_length=100)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidades', to='municipio.municipio')),
            ],
            options={
                'db_table': 'localidad',
            },
        ),
    ]
