# Generated by Django 5.1.3 on 2024-12-05 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
