# Generated by Django 5.1.4 on 2024-12-12 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localidad', '0002_alter_localidad_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_length', message='El ID debe tener entre 8 y 10 dígitos.', regex='^\\d{8,10}$')]),
        ),
    ]
