# Generated by Django 5.0.2 on 2026-02-22 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('lista_precios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='lista_precios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lista_precios.listaprecios'),
        ),
    ]
