# Generated by Django 5.1.1 on 2024-11-26 18:38

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),  # Aquí coloca la dependencia de tu migración inicial
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Eliminar las claves foráneas
            ALTER TABLE cliente DROP FOREIGN KEY cliente_localidad_id_8f7c297b_fk_localidad_id;
            ALTER TABLE localidad DROP FOREIGN KEY localidad_municipio_id_467125c2_fk_municipio_id;
            ALTER TABLE municipio DROP FOREIGN KEY municipio_provincia_id_a7463107_fk_provincia_id;

            -- Eliminar las tablas
            DROP TABLE IF EXISTS localidad CASCADE;
            DROP TABLE IF EXISTS municipio CASCADE;
            DROP TABLE IF EXISTS provincia CASCADE;
            """,
            reverse_sql="""
            -- Sentencias para revertir las eliminaciones en caso de ser necesario
            CREATE TABLE provincia (
                id INT PRIMARY KEY,
                -- Agregar las demás columnas necesarias
            );

            CREATE TABLE municipio (
                id INT PRIMARY KEY,
                provincia_id INT,
                -- Agregar las demás columnas necesarias
                FOREIGN KEY (provincia_id) REFERENCES provincia(id)
            );

            CREATE TABLE localidad (
                id INT PRIMARY KEY,
                municipio_id INT,
                -- Agregar las demás columnas necesarias
                FOREIGN KEY (municipio_id) REFERENCES municipio(id)
            );

            ALTER TABLE cliente ADD CONSTRAINT cliente_localidad_id_8f7c297b_fk_localidad_id FOREIGN KEY (localidad_id) REFERENCES localidad(id);
            """
        ),
    ]

    atomic = False
