# Generated by Django 5.1.1 on 2024-11-26 18:38

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_eliminar_relaciones_localidad'),  # Asegúrate de que la dependencia sea la última migración
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE cliente DROP COLUMN localidad_id;
            """,
            reverse_sql="-- Aquí iría la sentencia para revertir la eliminación de la columna si fuera necesario"
        ),
    ]