# Generated by Django 5.1.1 on 2024-11-26 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_cliente_domicilio'),
        ('cliente', '0004_eliminar_columna_localidad'),
    ]

    operations = [
    ]
