# Generated by Django 5.1.3 on 2024-11-30 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banco', '0001_initial'),
        ('pago', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_emision', models.DateField()),
                ('fecha_deposito', models.DateField(blank=True, null=True)),
                ('check_deposito', models.BooleanField(blank=True, null=True)),
                ('acreditado', models.BooleanField(default=False)),
                ('fecha_deposito_pago', models.DateField(blank=True, null=True)),
                ('check_pago_proveedor', models.BooleanField(default=False)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.banco')),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pago.pago')),
            ],
            options={
                'db_table': 'cheque',
            },
        ),
    ]
