# Generated by Django 5.0.2 on 2026-03-02 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factura', '0001_initial'),
        ('producto', '0001_initial'),
        ('tipo_venta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaProducto',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_bulto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producto.producto')),
                ('tipo_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipo_venta.tipoventa')),
            ],
            options={
                'db_table': 'factura_producto',
            },
        ),
    ]
