# Generated by Django 5.1.5 on 2025-02-24 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factura', '0001_initial'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaProducto',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('cantidad_producto', models.FloatField(blank=True, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('precio_bulto', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='factura.factura')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
            options={
                'db_table': 'factura_producto',
            },
        ),
    ]
