# Generated by Django 5.0.2 on 2026-03-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0001_initial'),
        ('factura_producto', '0002_refactor_precio_aplicado'),
        ('producto', '0002_alter_producto_cantidad_por_bulto_and_more'),
        ('tipo_venta', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='facturaproducto',
            constraint=models.UniqueConstraint(fields=('factura', 'producto'), name='unique_producto_por_factura'),
        ),
    ]
