# Generated by Django 5.0.2 on 2026-03-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_unidad', '0002_add_abreviacion_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipounidad',
            name='tipo_medicion',
            field=models.CharField(blank=True, choices=[('CANTIDAD', 'Cantidad'), ('PESO', 'Peso')], max_length=10, null=True),
        ),
    ]
