# Generated by Django 5.0.2 on 2026-03-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_unidad', '0003_tipounidad_tipo_medicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipounidad',
            name='tipo_medicion',
            field=models.CharField(choices=[('CANTIDAD', 'Cantidad'), ('PESO', 'Peso')], max_length=10),
        ),
    ]
