# Generated by Django 5.0.2 on 2026-04-18 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banco', '0001_initial'),
        ('proveedor', '0003_proveedor_cuenta_corriente_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnCheck',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('EMITIDO', 'Emitido'), ('COBRADO', 'Cobrado'), ('ANULADO', 'Anulado')], default='EMITIDO', max_length=20)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.banco')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveedor.proveedor')),
            ],
            options={
                'db_table': 'cheque_propio',
            },
        ),
    ]
