# Generated by Django 5.0.2 on 2026-04-18 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
        ('cheque_propio', '0001_initial_own_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owncheck',
            name='banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banco.banco'),
        ),
    ]
