# Generated by Django 5.0.2 on 2026-04-20 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheque_propio', '0002_protect_banco_fk'),
        ('pago_compra', '0002_add_tipo_pago_fecha_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owncheck',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='owncheck',
            name='pago_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pago_compra.pagocompra'),
        ),
    ]
