# Generated by Django 5.1.5 on 2026-08-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheque_propio', '0004_remove_pago_compra_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='owncheck',
            name='fecha_deposito',
            field=models.DateField(blank=True, null=True),
        ),
    ]
