# Generated by Django 5.1.1 on 2024-11-22 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factura', '0001_initial'),
        ('pago', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe_abonado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.factura')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pago.pago')),
            ],
            options={
                'db_table': 'pago_factura',
            },
        ),
    ]
