# Generated by Django 5.0.2 on 2026-03-17 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago_cliente', '0001_initial'),
        ('pago_factura', '0003_pagofactura_add_pago_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagofactura',
            name='pago_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pago_cliente.pagocliente'),
        ),
    ]
