# Generated by Django 5.1.3 on 2024-11-30 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mercado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('puesto', models.SmallIntegerField()),
                ('nave', models.SmallIntegerField()),
                ('telefono', models.CharField(max_length=20)),
                ('cuenta_corriente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_fantasia', models.CharField(max_length=50)),
                ('mercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.mercado')),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
    ]
