# Generated by Django 5.1.5 on 2026-03-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='nave',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
