# Generated by Django 5.0.2 on 2026-03-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Venta',
                'verbose_name_plural': 'Tipos de Venta',
                'db_table': 'tipo_venta',
            },
        ),
    ]
